name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: |
          docker build -t web-rust-frontend:latest ./frontend
          docker build -t web-rust-backend:latest ./backend
          docker save web-rust-frontend:latest web-rust-backend:latest | gzip > images.tar.gz

      - name: Copy Images and Config to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          source: "images.tar.gz,docker-compose.yml"
          target: "/root/web-rust"

      - name: Load and Restart Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            cd ~/web-rust
            
            echo "Cargando nuevas imagenes de Docker..."
            docker load -i images.tar.gz
            rm images.tar.gz
            
            echo "Reiniciando servicios..."
            docker compose up -d --no-build
